import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shop-Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" type="image/png" />
      </Head>

      <main className={styles.main}>
        <div className={styles.Navbar}>
          <div className={styles.photolog}>
            <Image
              src="/logo.png"
              width={70}
              height={65}
              className={styles.logo}
            />
          </div>

          <div className={styles.flexing}>
            <input
              type="search"
              placeholder="Search"
              className={styles.Searchinginput}
            ></input>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="25"
              height="25"
              fill="black"
              class="bi bi-search"
              className={styles.cursor}
              viewBox="0 0 16 16"
            >
              <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
            </svg>
          </div>

          <div className={styles.cursor} >
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="black" class="bi bi-cart4" viewBox="0 0 16 16" >
              <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z" />
            </svg>

            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="black" class="bi bi-person-fill " viewBox="0 0 16 16" className={styles.margining} >
              <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
            </svg>

            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="black" class="bi bi-calendar2-heart" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M4 .5a.5.5 0 0 0-1 0V1H2a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2h-1V.5a.5.5 0 0 0-1 0V1H4V.5ZM1 3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V3Zm2 .5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V4a.5.5 0 0 0-.5-.5H3Zm5 4.493c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132Z" />
            </svg>
          </div>
        </div>

        <center>
          <Image
            height={600}
            width={1300}
            src='/backimg.png' />
        </center>

        <h1 className={styles.Heading}>All Categories</h1>

        <div className={styles.Box}>

          <div className={styles.MainBox}>

            <div className={styles.Imageboxtext}>
              <Image
                src='/home.png'
                width={400}
                height={350}
              />
              <h1>Home Furniture</h1>
            </div>

            <div className={styles.Imageboxtext}>
              <Image
                src='/elec.png'
                width={400}
                height={350}
              />
              <h1>Electronics</h1>
            </div>

          </div>

        </div>

        <h1 className={styles.Heading}>Footer Section</h1>

        <div className={styles.Footer}>

          <div>
            <h2>Contact</h2>
            <h5><li>Instagram</li></h5>
            <h5><li>Facebook</li></h5>
            <h5><li>Twitter</li></h5>
          </div>

          <div>
            <h2>About</h2>
            <h5><li>Pdf</li></h5>
            <h5><li>Documentation</li></h5>
            <h5><li>Teams&Conditions</li></h5>
          </div>

          <div>
            <h2>Payment</h2>
            <h5><li>DebitCard</li></h5>
            <h5><li>CreditCard</li></h5>
            <h5><li>UPI's</li></h5>
          </div>

        </div>

      </main>
    </div>
  );
}
